### ISSUE TITLE
js调用android方法后  回调没有调用

### ISSUE THREAD

**Issue by blazert** [lzyzsd/JsBridge#124]
前端使用的是vue但页面应用，调用native方法后，回调方法没有进去 这是什么问题

**Comment by contineu0818** [comment]
我用react做前端，遇到一样的问题

**Comment by contineu0818** [comment]
@blazert 我解决这个问题了，需要在最外层的html文件中手动插入一个<script>标签

<script>
function connectWebViewJavascriptBridge(callback) {
        if (window.WebViewJavascriptBridge) {
            callback(WebViewJavascriptBridge)
        } else {
            document.addEventListener(
                'WebViewJavascriptBridgeReady'
                , function() {
                    callback(WebViewJavascriptBridge)
                },
                false
            );
        }
    }
</script>

**Comment by blazert** [comment]
@contineu0818  嗯  我也是  谢谢
