### ISSUE TITLE
org.json.JSONException: Unterminated object at character

### ISSUE THREAD

**Issue by nashxk** [lzyzsd/JsBridge#14]
org.json.JSONException: Unterminated object at character 51 of [{"responseId":"JAVA_CB_4_2099","responseData":"{"isCanBuy":false,"tempOrderVO":{"orderStoreViewList":[{"goodsAmount":158,"baseGoodsAmount":258,"oriGoodsAmount":158,"goodsViewList":[{"id":287001,"goodsPrice":14,"basePrice":24,"storeId":1000},{"id":287015,"goodsPrice":16,"basePrice":26,"storeId":1000}],"storeId":"1000","orderAmount":158,"baseOrderAmount":258,"oriOrderAmount":158,"discountAmount":100}],"allOrderAmount":"158.00","allBaseOrderAmount":"258.00","allOriOrderAmount":"158.00","discountAmount":"100.00"}}"}]

在解析的时候出错。
Android4.4以上版本正常，4.4一下版本出错。

**Comment by lzyzsd** [comment]
使用jitpack获取最新版即可
