### ISSUE TITLE
请问下面这个崩溃是JsBridge这个库造成的吗？

### ISSUE THREAD

**Issue by HolenZhou** [lzyzsd/JsBridge#15]
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread: Activity com.talkweb.cloudcampus.jsbridge.WebActivity has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@429edcd8 that was originally bound here
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread: android.app.ServiceConnectionLeaked: Activity com.talkweb.cloudcampus.jsbridge.WebActivity has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@429edcd8 that was originally bound here
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:979)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:873)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1818)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.ContextImpl.bindService(ContextImpl.java:1806)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.content.ContextWrapper.bindService(ContextWrapper.java:503)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.speech.tts.TextToSpeech.connectToEngine(TextToSpeech.java:687)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:656)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:609)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.webkit.AccessibilityInjector$TextToSpeechWrapper.<init>(AccessibilityInjector.java:696)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.webkit.AccessibilityInjector.addTtsApis(AccessibilityInjector.java:492)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.webkit.AccessibilityInjector.addAccessibilityApisIfNecessary(AccessibilityInjector.java:173)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.webkit.AccessibilityInjector.updateJavaScriptEnabled(AccessibilityInjector.java:427)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.webkit.WebViewClassic.updateJavaScriptEnabled(WebViewClassic.java:3523)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.webkit.WebSettingsClassic.setJavaScriptEnabled(WebSettingsClassic.java:1572)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at com.talkweb.cloudcampus.jsbridge.BridgeWebView.init(BridgeWebView.java:62)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at com.talkweb.cloudcampus.jsbridge.BridgeWebView.<init>(BridgeWebView.java:36)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at com.talkweb.cloudcampus.view.ProgressWebView.<init>(ProgressWebView.java:18)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at java.lang.reflect.Constructor.constructNative(Native Method)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.view.LayoutInflater.createView(LayoutInflater.java:600)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at com.talkweb.cloudcampus.ui.base.BaseActivity.onCreate(BaseActivity.java:64)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at com.talkweb.cloudcampus.ui.base.TitleActivity.onCreate(TitleActivity.java:25)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.Activity.performCreate(Activity.java:5369)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.ActivityThread.access$700(ActivityThread.java:165)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.os.Handler.dispatchMessage(Handler.java:99)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.os.Looper.loop(Looper.java:137)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at android.app.ActivityThread.main(ActivityThread.java:5450)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at java.lang.reflect.Method.invokeNative(Native Method)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at java.lang.reflect.Method.invoke(Method.java:525)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
10-13 10:03:54.830 18254-18254/com.talkweb.cloudcampus E/ActivityThread:     at dalvik.system.NativeStart.main(Native Method)

**Comment by lzyzsd** [comment]
应该不是，你有资源未释放
