### ISSUE TITLE
如何判断js方法存不存在？

### ISSUE THREAD

**Issue by thsai** [lzyzsd/JsBridge#151]

**Comment by KaelInvoker** [comment]
同问

**Comment by huangchaoqingcheng** [comment]
> _createQueueReadyIframe(doc)
> _createQueueReadyIframe4biz(doc)
> init(messageHandler)
> send(data, responseCallback)
> ...
> _handleMessageFromNative(messageJSON)
> 最直接看assets下的js文件。不会要写一个保存所有方法名的数组里面进行判断吧？ @huangchaoqingcheng @KaelInvoker

通过原生的方式注入js的一个方法（即检查方法是否存在的js方法）
然后原生在需要判断的时候与js通信 调用一下这个检查的方法

**Comment by jokerLee2013** [comment]
理论上讲，混合开发不应该有这种问题，我猜你应该是遇到了版本兼容问题了，如果是这样的话，可以让原生提供一个桥，通过这个桥获取app的版本信息，然后根据版本信息可以判断哪些方法有，哪些方法没有

**Comment by OsbornWJ** [comment]
同问  在BridgeWebView中如何判断一个js方法是否存在

**Comment by lzyzsd** [comment]
if(typeof yourfunctionname === 'function'){
    //存在且是function
} else{
   //不存在或不是function
}

和web开发中常用的检测方法一致
