### ISSUE TITLE
webView.callHandler()方法时好时坏，有时根本没反应

### ISSUE THREAD

**Issue by 1528992118** [lzyzsd/JsBridge#154]
<pre>
  private void warnListRefresh() {
        webView.callHandler("warnListRefresh", "refresh", new CallBackFunction() {
            @Override
            public void onCallBack(String data) {

                if (StringUtil.isEmpty(data))
                    return;
                if (MessageTypeEnum.TYPE_EJCDS.getKey().equals(data))
                    EventBus.getDefault().post(AppEventTypeEnum.CLEAN_EJCDS_MSG_LIST.getKey());

            }
        });
    }
</pre>
我这边需要接收到刷新通知后，需要主动调用Js中的刷新方法，刷新当前页面，但实际使用中，有时有效，有时没效果。有效果，也是上一次刷新通知。其中我可能做错的地方：
`前台是用的Vue，并且是远程加载的h5地址，他反应本地测试的时候（并不在Android下的WebView中，他直接跑的Vue项目），老是找不到WebViewJavascriptBridge这个对象，所以我给他的前台h5项目了一个WebViewJavascriptBridge.js`

**Comment by Longalei** [comment]
首先，第一点，有效果是在上一次刷新通知。我理解的意思是再一次接收到刷新通知时js方法没执行。确定一下再一次接收到刷新的通知是否从主线程发出？
第二点。这个项目是在android.webkit;下的webview中通过拦截url实现java与js通讯的。并且在页面加载的onpageFinish（）方法中注册了js文件。你不在webview中跑，当然有可能找不到相应的js对象。
