### ISSUE TITLE
使用了jsbridge和原生H5拉起微信支付冲突怎么办？

### ISSUE THREAD

**Issue by Hunter2916** [lzyzsd/JsBridge#176]
使用jsbridge导致Android原生拉起微信H5支付失败，直接空白页，注销掉jsbridge就可以了，怎么解决

**Comment by j1453** [comment]
微信H5支付失败也分多种情况，你起码要描述一下是哪种错误

**Comment by MapleSunFLY** [comment]
js 中_doSend(message, responseCallback)发送请求后 shouldOverrideUrlLoading 方法并未被调用
