### ISSUE TITLE
关于设置webviewclient后不能与js互调问题

### ISSUE THREAD

**Issue by scaPEGoatno** [lzyzsd/JsBridge#18]
这个    问题 怎么解决?

**Comment by lzyzsd** [comment]
请让你的WebView继承自BridgeWebView，同时你可以override generateBridgeWebViewClient方法，这里返回的WebViewClient继承自BridgeWebViewClient就可以了

**Comment by addappcn** [comment]
这样设置还是不能通信，大佬  求助

**Comment by addappcn** [comment]
scaPEGoatno   兄弟 怎么解决的

**Comment by addappcn** [comment]
@scaPEGoatno 给个你的联系方式

**Comment by lutao2599** [comment]
我也遇到了这个问题，请问解决了吗？

**Comment by ff-frida** [comment]
> 我也遇到了这个问题，请问解决了吗？

不要使用继承，我这边是直接拿代码过来，自己处理一次，client直接和平时一样写就好了。
