### ISSUE TITLE
是不是漏提交了一些类啊，demo都跑不起来呐。

### ISSUE THREAD

**Issue by Zeng-Ke** [lzyzsd/JsBridge#197]

**Comment by jimneylee** [comment]
我这边也遇到一样的问题，之前项目有继承好老版本，新的版本确实跑不起来。细看了最近的几个 pull request 合并，先后顺序有点问题，优先合并了 #187 请求，改动比较大，后面合并和 #184 #186 需要的一些 CallBackFunction 接口文件都已在 #187 时去掉了。可以直接在 #187 这个合并地方 clone 一个版本，或者到 [kingwang666/JsBridge/tree/api17](https://github.com/kingwang666/JsBridge/tree/api17)获取。 @Zeng-Ke

**Comment by fengchuxiaodai** [comment]
我试着合并了下，新老版本感觉弄混了，有方法替换和类替换
现在是自己写了，没有用这个轮子，本来想偷懒的，没想到……

**Comment by smallbuer** [comment]
已经按照作者的思路重构了项目，可以参考：https://github.com/smallbuer/JSBridge-Android
