### ISSUE TITLE
怎么判断交互的另一端有没有某一个方法

### ISSUE THREAD

**Issue by zhangshilei0213** [lzyzsd/JsBridge#198]
j比如客户端调取安卓的某个不存在的方法，根本没法检测它是否存在，现在的解决方案是用的版本号做的控制，但是不能从根本上解决问题，大家有什么好的方案吗

**Comment by hayye** [comment]
老哥解决了吗？

**Comment by lzyzsd** [comment]
type of xxfunction == function
