### ISSUE TITLE
引入有问题，源码也有问题

### ISSUE THREAD

**Issue by fengchuxiaodai** [lzyzsd/JsBridge#200]
1，引入轮子，不添加assets中的js，发现h5可以正常调用java，但是收不到回调，java不能调用h5
2，添加assets中的js，发现java可以正常调用h5，但是h5不能调用java
3，下载源码，发现报错，对比之前的版本，有些类缺失，有些方法缺失
以上问题是我接入jsbridge发现的问题，烦请作者有空改下吧

**Comment by clunyes** [comment]
> 1，引入轮子，不添加assets中的js，发现h5可以正常调用java，但是收不到回调，java不能调用h5
> 2，添加assets中的js，发现java可以正常调用h5，但是h5不能调用java
> 3，下载源码，发现报错，对比之前的版本，有些类缺失，有些方法缺失
> 以上问题是我接入jsbridge发现的问题，烦请作者有空改下吧

之前用的好好地，现在怎么接入都有问题了。。。

**Comment by xybCoder** [comment]
我也是native调用js,回调没有反应
