### ISSUE TITLE
registerHandler是去掉了吗

### ISSUE THREAD

**Issue by clunyes** [lzyzsd/JsBridge#202]
我看最新库，已经不用这个方法了

**Comment by shegang** [comment]
我一遇到了，调用这个方法没有反应

**Comment by clunyes** [comment]
> 我一遇到了，调用这个方法没有反应

嗯，已经换库了。。

**Comment by Young-Wang** [comment]
> > 我一遇到了，调用这个方法没有反应
> 
> 嗯，已经换库了。。

遇到同样的问题，求问你现在换成哪个库了
