### ISSUE TITLE
☚☛是谁删除代码没测试还是漏提交代码了还是谁和谁代码冲突了！！！

### ISSUE THREAD

**Issue by jaydroid1024** [lzyzsd/JsBridge#203]
![image](https://user-images.githubusercontent.com/18594480/69405081-b8073b00-0d39-11ea-92ed-f0c1dbf8e488.png)

**Comment by Jenkyn** [comment]
是合并这个分PR导致的：https://github.com/lzyzsd/JsBridge/commit/914840315588b9bcf84cf3bc58a94782a48a8c85
 这个PR质量很低（删除了很多必要代码，无关的zip文件也添加到工程里，文件改乱码了也往里放，删除必要的缩进），不知作者为何也合并。
