### ISSUE TITLE
☛是代码冲突导致的吗☚，少文件了吧

### ISSUE THREAD

**Issue by jaydroid1024** [lzyzsd/JsBridge#204]
CallBackFunction
BridgeHandler
Message
.....

**Comment by Jenkyn** [comment]
是合并这个分PR导致的：https://github.com/lzyzsd/JsBridge/commit/914840315588b9bcf84cf3bc58a94782a48a8c85
 这个PR质量很低（删除了很多必要代码，无关的zip文件也添加到工程里，文件改乱码了也往里放，删除必要的缩进），不知作者为何也合并。

前面有人提ISSUE了

**Comment by zaccheow** [comment]
我也碰上了，折腾一下午了
