### ISSUE TITLE
出现代码缺的，请回滚代码

### ISSUE THREAD

**Issue by severaldays** [lzyzsd/JsBridge#217]
请回滚至到“2019-07-10 19:01” 之前的代码

**Comment by severaldays** [comment]
2019-07-10 19:01提到这条patch 改动较大，有经过测试没，稳定不

**Comment by Geek-Spirit** [comment]
如果我通过implementation 'com.github.lzyzsd:jsbridge:1.0.4' 这个方式引入的话 还是最新的代码吗?我下载了 “2019-07-10 19:01” 之前的代码,是可以运行的,现在我想引入工程里面.

**Comment by gycold** [comment]
确实有问题，demo跟lib不一致
