### ISSUE TITLE
js注册了函数java调用其中部分代码无效没执行

### ISSUE THREAD

**Issue by MarsDiplomatToEarth** [lzyzsd/JsBridge#222]
WebViewJavascriptBridge.registerHandler("functionInJs", function(data, responseCallback) {
console.log(123)
        responseCallback(responseData);
    });

console.log(123)这句不执行 其中代码我测试了一下都不执行不知道为啥 求解

**Comment by NateRobinson** [comment]
我好像也遇到了

**Comment by MarsDiplomatToEarth** [comment]
加个qq交流一下怎么样

**Comment by NateRobinson** [comment]
我在尝试这个库了：[https://github.com/wendux/DSBridge-Android/blob/master/readme-chs.md](https://github.com/wendux/DSBridge-Android/blob/master/readme-chs.md)  当前这个库看着作者已经停止维护了。

**Comment by smallbuer** [comment]
如果JS文件执行问题，请参考[https://github.com/smallbuer/JSBridge-Android](url)，里面有一个优化后的Js，看是否可以解决您的问题；

**Comment by tghjnjvg** [comment]
还是不行

**Comment by xukunn** [comment]
有一次大的提交,js调用java换成@JavascriptInterface方式后,js文件中 ,有个"this", 替换成 "window.android". 因为this关键字在javascript中设计的不好
