### ISSUE TITLE
使用了一阵时间，遇到的一些bug，发现框架有问题。建议使用https://github.com/wendux/DSBridge-Android.git

### ISSUE THREAD

**Issue by namjkee** [lzyzsd/JsBridge#225]
建议使用https://github.com/wendux/DSBridge-Android.git

**Comment by kaikaifly** [comment]
@woaixj 什么问题呢

**Comment by Dora0512** [comment]
> 建议使用https://github.com/wendux/DSBridge-Android.git
这个库作者好久没更新了，不知还能使用不

**Comment by visualzhang** [comment]
这个问题很多，刚开始就一堆，后来要上线发现很不稳定，赶紧换https://github.com/wendux/DSBridge-Android.git

**Comment by is1988** [comment]
> 建议使用https://github.com/wendux/DSBridge-Android.git

DSBridge   18年就开始用了 当初看他也支持iOS的，但是最近作者没更新，对于Android10以上的设备适配并不是很完美，之前项目用的是加载本地html用ajax请求数据渲染在webview上，要说稳定性吧还是推荐DSBridge，用了三年了。
