### ISSUE TITLE
js报错

### ISSUE THREAD

**Issue by MorpheusChan** [lzyzsd/JsBridge#227]
使用java调用js代码时，报了一下错误，请问是使用方法有问题吗
WebViewJavascriptBridge: WARNING: javascript handler threw. {callbackId: "JAVA_CB_8_2576", data: "2", handlerName: "functionInJs"} TypeError: handler is not a function
    at <anonymous>:1:3120

**Comment by MorpheusChan** [comment]
感谢你的来信，保持联系。

**Comment by binbin821** [comment]
我也遇到了同样的问题，请问是怎么解决的呢？
