### ISSUE TITLE
项目源码缺少BridgeHandler以及其他类

### ISSUE THREAD

**Issue by Zhangzhenguo-git** [lzyzsd/JsBridge#228]
可能没有把文件上传全部

**Comment by AntoineLee** [comment]
看前面，回退到19.7.10那个版本以前

**Comment by smallbuer** [comment]
To see [https://github.com/smallbuer/JSBridge-Android](url)

**Comment by gengsena** [comment]
回退到19.7.7的版本就可以  ID:576336aa......

**Comment by kunlinyu** [comment]
Author: wxj <wangxiaojielove666@gmail.com>  2019-07-10 19:01:25
Committer: wxj <wangxiaojielove666@gmail.com>  2019-07-10 19:01:25
Parent: aca02b460ebc5a7c121e9b202bb49c3ce32ba1d1 (Merge pull request #118 from hyy12345678/master)
Child:  a643f0979f042150b262fb692a4dfa0663b276a1 (Merge pull request #187 from kingwang666/api17)
Branches: master, remotes/origin/master
Follows: 1.0.4
Precedes: 

    最小api为17（google修复了js的安全性漏洞），改用默认android默认js接口对接方式




This patch delete that file.
Does anybody know why?
