### ISSUE TITLE
错误: 找不到符号CallBackFunction

### ISSUE THREAD

**Issue by AttITuder** [lzyzsd/JsBridge#233]
.java:27: 错误: 找不到符号
    private Map<String, CallBackFunction> responseCallbacks = new HashMap<>();
                        ^
  符号:   类 CallBackFunction
  位置: 类 BridgeHelper
/Users/dpc/Desktop/code/JsBridge/library/src/main/java/com/github/lzyzsd/jsbridge/BridgeHelper.java:28: 错误: 找不到符号
    private Map<String, BridgeHandler> messageHandlers = new HashMap<>();
                        ^
  符号:   类 BridgeHandler
  位置: 类 BridgeHelper
/Users/dpc/Desktop/code/JsBridge/library/src/main/java/com/github/lzyzsd/jsbridge/BridgeHelper.java:29: 错误: 找不到符号
    private BridgeHandler defaultHandler = new DefaultHandler();
            ^
  符号:   类 BridgeHandler
  位置: 类 BridgeHelper
/Users/dpc/Desktop/code/JsBridge/library/src/main/java/com/github/lzyzsd/jsbridge/BridgeHelper.java:31: 错误: 找不到符号
    private List<Message> startupMessage = new ArrayList<>();
                 ^

**Comment by jacky1234** [comment]
我也是的

**Comment by kuaitao** [comment]
x打开就是报错的
