### ISSUE TITLE
android.view.InflateException: Binary XML file line #58

### ISSUE THREAD

**Issue by daomeixiong2547** [lzyzsd/JsBridge#234]
sometimes happened,not always.
i reloaded app solved this problem,.
what caused this???

**Comment by RDSunhy** [comment]
这个bug解决了吗？

**Comment by daomeixiong2547** [comment]
> 这个bug解决了吗？

我这个不是必现的，我们测试人员使用中突然出现，重新安装后不再出现，但是不知道是什么原因造成的，你也遇到了吗？？？

**Comment by daomeixiong2547** [comment]
> 这个bug解决了吗？

我查了一下友盟报错日志，这个报错后面跟着的报错是同时使用极光推送和webview，Android P之后不同进程使用相同目录会有webview的bug，我解决了那个问题。
