### ISSUE TITLE
改的什么东西

### ISSUE THREAD

**Issue by Lion7k** [lzyzsd/JsBridge#235]
哪个智障改的代码

**Comment by Sworgod** [comment]
@Lion7k 就是，我也想说。这不是害人吗？像我这种自学的初学者，岂不是故意想让我吐血的吗。

**Comment by sunwen0402** [comment]
已经改的面目全非了...... 不过看里面的注释应该是这两个人干的
/**
 * Created on 2019/7/10.
 * Author: bigwang
 * Description:
 */
 
 /**
 * WebView功能接口.
 *
 * @author ZhengAn
 * @date 2019-07-01
 */

**Comment by Joecao123** [comment]
> 已经改的面目全非了...... 不过看里面的注释应该是这两个人干的
> /**
> 
> * Created on 2019/7/10.
> * Author: bigwang
> * Description:
>   */
> 
> /**
> 
> * WebView功能接口.
> * @author ZhengAn
> * @Date 2019-07-01
>   */

卧龙和凤雏

**Comment by fmway123** [comment]
已收到^_^
