### ISSUE TITLE
为什么把类都给删除了？

### ISSUE THREAD

**Issue by skyofsky** [lzyzsd/JsBridge#236]
failed
:library:compileDebugJavaWithJavac
library/src/main/java/com/github/lzyzsd/jsbridge/BridgeHelper.java
错误: 找不到符号
符号:   类 CallBackFunction
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 BridgeHandler
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 BridgeHandler
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 Message
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 Message
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 Message
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 BridgeHandler
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 CallBackFunction
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 CallBackFunction
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 Message
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 Message
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 CallBackFunction
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 BridgeHandler
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 CallBackFunction
位置: 类 BridgeHelper
错误: BridgeHelper不是抽象的, 并且未覆盖WebViewJavascriptBridge中的抽象方法sendToWeb(String,Object...)
错误: 找不到符号
符号:   类 DefaultHandler
位置: 类 BridgeHelper
错误: 找不到符号
符号:   方法 getFunctionFromReturnUrl(String)
位置: 类 BridgeUtil
错误: 找不到符号
符号:   类 CallBackFunction
位置: 类 BridgeHelper
错误: 找不到符号
符号:   方法 getDataFromReturnUrl(String)
位置: 类 BridgeUtil
错误: 方法不会覆盖或实现超类型的方法
错误: 方法不会覆盖或实现超类型的方法
错误: 找不到符号
符号:   类 Message
位置: 类 BridgeHelper
错误: 找不到符号
符号:   类 Message
位置: 类 BridgeHelper
错误: 找不到符号
符号:   变量 JS_FETCH_QUEUE_FROM_JAVA
位置: 类 BridgeUtil
错误: 找不到符号
符号:   类 CallBackFunction
位置: 类 BridgeHelper
错误: 找不到符号
符号:   方法 parseFunctionName(String)
位置: 类 BridgeUtil
错误: 找不到符号
符号:   类 Message
位置: 类 BridgeHelper
错误: 找不到符号
符号:   变量 YY_RETURN_DATA
位置: 类 BridgeUtil
错误: 找不到符号
符号:   变量 YY_OVERRIDE_SCHEMA
位置: 类 BridgeUtil
library/src/main/java/com/github/lzyzsd/jsbridge/BridgeWebView.java
错误: 找不到符号
符号:   类 CallBackFunction
位置: 类 BridgeWebView
错误: 找不到符号
符号:   类 BridgeHandler
位置: 类 BridgeWebView
错误: 找不到符号
符号:   类 BridgeHandler
位置: 类 BridgeWebView
错误: 找不到符号
符号:   类 HashMap
位置: 类 BridgeWebView
错误: 找不到符号
符号:   类 CallBackFunction
位置: 类 BridgeWebView
错误: 找不到符号
符号:   类 HashMap
位置: 类 BridgeWebView
错误: 找不到符号
符号:   类 BridgeHandler
位置: 类 BridgeWebView
错误: 找不到符号
符号:   类 DefaultHandler
位置: 类 BridgeWebView

**Comment by ludongya** [comment]
https://github.com/kingwang666/JsBridge
