### ISSUE TITLE
请教下JsBridge源码问题

### ISSUE THREAD

**Issue by xxchenqi** [lzyzsd/JsBridge#237]
1、native通过loadurl方式执行js方法，并且生成回调ID，保存到map(id,CallBack)。

2、js匹配到方法后执行，创建回调对象，生成message存入到队列里。
在通过iframe通知native取消息

3、native拦截到协议后，再次创建回调(用来解析队列)，保存到map(_fetchQueue,CallBack)，通过loadUrl执行js的_fetchQueue

4、js执行_fetchQueue，将messageQueue转换成json，放到iframe的src中，通知native取消息。

5、native拦截到协议后，取出map的回调（_fetchQueue），将messageQueue转成集合遍历，取出message的回调id，通过id取出map的CallBack，执行完成回调。

那么为什么需要这么多步骤？

native调用js时，直接将需要回调的方法名称或ID，给到JS，JS执行完之后，在调用native的方法就可以了。

**Comment by smallbuer** [comment]
> 1、native通过loadurl方式执行js方法，并且生成回调ID，保存到map(id,CallBack)。
> 
> 2、js匹配到方法后执行，创建回调对象，生成message存入到队列里。
> 在通过iframe通知native取消息
> 
> 3、native拦截到协议后，再次创建回调(用来解析队列)，保存到map(_fetchQueue,CallBack)，通过loadUrl执行js的_fetchQueue
> 
> 4、js执行_fetchQueue，将messageQueue转换成json，放到iframe的src中，通知native取消息。
> 
> 5、native拦截到协议后，取出map的回调（_fetchQueue），将messageQueue转成集合遍历，取出message的回调id，通过id取出map的CallBack，执行完成回调。
> 
> 那么为什么需要这么多步骤？
> 
> native调用js时，直接将需要回调的方法名称或ID，给到JS，JS执行完之后，在调用native的方法就可以了。

JS队列是为了保持调用顺序有序的进行，直接调用是可以实现，但是对于高并发场景会出现问题
