### ISSUE TITLE
Error inflating class com.github.lzyzsd.jsbridge.BridgeWebView

### ISSUE THREAD

**Issue by OOOOOldZhu** [lzyzsd/JsBridge#238]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.junxin.zeropay/com.junxin.zeropay.activity.main.WebActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class com.github.lzyzsd.jsbridge.BridgeWebView Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003 at com.junxin.zeropay.activity.base.BaseActivity.onCreate(BaseActivity.java:6)

设备机型:
vivo
是否Root:
否
地域:
中国河南省开封市
机型版本:
vivo X6S A
设备电量:
61.0
电池温度:
257.0
渠道信息:
xxx
磁盘可用占比:
45.48
内存可用占比:
4.57
现在是2020.12.14，看来这个问题是没有解决办法了？

**Comment by smallbuer** [comment]
此库作者已没有维护了，可以按照[JSBridge-Android](https://github.com/smallbuer/JSBridge-Android)进行升级更新，希望对你有帮助

**Comment by dntil** [comment]
我在5.0，5.1上遇到，是因为使用了androidx.appcompat:appcompat:1.1.0，升级即可
