### ISSUE TITLE
我已经重构了这个库，10分钟就能完成接入,也许可以帮助你.

### ISSUE THREAD

**Issue by housenkui** [lzyzsd/JsBridge#258]
我已经重构了这个库，10分钟就能完成接入,也许可以帮助你.
而且还有视频一步一步的介绍.

Java:
https://github.com/SDBridge/SDBridgeJava
Kotlin:
https://github.com/SDBridge/SDBridgeKotlin

**Comment by junkai-L** [comment]
不行，直接报Uncaught ReferenceError: WebViewJavascriptBridge is not defined 错误

**Comment by housenkui** [comment]
看这个视频介绍：
https://search.bilibili.com/all?vt=53806197&keyword=SDBridgeKotlin&from_source=webtop_search&spm_id_from=333.788

第5个常见问题.有说明，当原生挂载是不成功的时候，h5自己挂载.

**Comment by housenkui** [comment]
@junkai-L

**Comment by sing1** [comment]
啥时候出个Flutter的插件
