### ISSUE TITLE
WebViewJavascriptBridgem和jsbridge 一致性

### ISSUE THREAD

**Issue by kingfeng** [lzyzsd/JsBridge#40]
你好，发现jsbridge基本和[https://github.com/marcuswestin/WebViewJavascriptBridge](url)基本一致，请问要统一使用的话，WebViewJavascriptBridge 需要修改哪些地方

**Comment by maobon** [comment]
webViewJavascriptBridge 看起来更像是IOS专属框架 Android 是在其基础上二次封装改造的

**Comment by markzhai** [comment]
@kingfeng 可以用同一份js，改一下jsbridge的前缀scheme就行了

**Comment by imaiya** [comment]
请问具体如何实现呢
