### ISSUE TITLE
js获取android端数据，数据只能传递一个字符串吗？

### ISSUE THREAD

**Issue by MhuiHugh** [lzyzsd/JsBridge#46]
function.onCallBack(“这是字符串”);  我传递一个json数据，js端接收到的json内容被作为responseData的value。 并自动加入转义字符，能不能和ios的开源项目一样可以传递自己的jsonObject?

**Comment by ishamkdk** [comment]
使用JSON对象。为了避免转义字符，在JS代码中使用Json.parse（数据）

**Comment by MhuiHugh** [comment]
ok,thanks
