### ISSUE TITLE
汉字传输

### ISSUE THREAD

**Issue by echolong** [lzyzsd/JsBridge#9]
@lzyzsd  发送汉字给java回报数据解析错误？

**Comment by echolong** [comment]
在WebViewJavaScriptBridge.js 文件中 messagingIframe.src = CUSTOM_PROTOCOL_SCHEME + '://return/_fetchQueue/' + escape(messageQueueString);
不用escape编码格式，直接使用数据 这样可以不 @lzyzsd ?

**Comment by lzyzsd** [comment]
必须要转义，不然可能会有比如/ 之类的字符

**Comment by echolong** [comment]
现在参数中出现汉字，就会出现解析出错的问题能否解决掉？

**Comment by lzyzsd** [comment]
@echolong 我晚上看看

**Comment by xiangding1983** [comment]
确实，如果参数中有汉字，会是乱码。

**Comment by imliujun** [comment]
今天元旦节公司上线了一个H5活动，因为中文传过来是乱码解析崩溃，直接把活动下线了。。

**Comment by lzyzsd** [comment]
@imliujun 有重现代码么？

**Comment by imliujun** [comment]
@lzyzsd  #21 已经解决了该问题。
但是我有一个其他问题想请教一下，就是我能不能将一个close的issue给reopen？我在另外一个项目中发现了一个问题，想reopen一个issue

**Comment by lzyzsd** [comment]
@imliujun 可以的
