### ISSUE TITLE
在ViewPage+fragment+webView 里JsBridge失效

### ISSUE THREAD

**Issue by lucf1103** [lzyzsd/JsBridge#95]
你好，在fragmetn里的Webview使用就收不到对应的消息。在Activity里就能收到～ 
网上看到一些Viewpage中webView的JS加载失败的解决方式。用了不起效果。求指条明路。

**Comment by zhaoziliang01** [comment]
有解决方案吗

**Comment by zhaoziliang01** [comment]
@lucf1103 @lzyzsd

**Comment by HeLiHuang** [comment]
怎么解决的？
